### ISSUE TITLE
Dúvidas sobre a execução do demo

### ISSUE THREAD

**Issue by kellydosocorro** [grei-ufc/mosaik-demo-wesaac-2019#1]
Olá, eu gostaria de saber mais informações de como executar este demo. Acredito que os passos que eu estava seguindo estão certos, talvez necessariamente apenas esteja faltando alguns detalhes para a execução se completar, já que eu obtive alguns erros.

Os arquivos que foram executados:
```
- demo.py
- start_pade_agents.py
```

O primeiro arquivo mencionado, foi executado com o comando:
`python3 demo.py`

O segundo, foi executado com o comando:

`pade start-runtime start_pade_agents.py`

Porém ambos apresentaram erros (o demo.py no entanto, provavelmente em decorrência do start_pade_agents.py), sendo estes:

Erro apresentado ao executar **pade start-runtime start_pade_agents.py**:

```
Unhandled Error
Traceback (most recent call last):
  File "/teste-mosaik/lib/python3.7/site-packages/pade/misc/utility.py", line 57, in start_loop
    reactor.run()
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/internet/base.py", line 1272, in run
    self.mainLoop()
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/internet/base.py", line 1284, in mainLoop
    self.doIteration(t)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
    selectable.readConnectionLost(f)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/internet/tcp.py", line 307, in readConnectionLost
    self.connectionLost(reason)
  File "/teste-mosaik/lib/python3.7/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/teste-mosaik/lib/python3.7/site-packages/pade/core/agent.py", line 94, in connectionLost
    self.fact.react(message)
  File "/teste-mosaik/lib/python3.7/site-packages/pade/core/sniffer.py", line 90, in react
    content = loads(message.content)
builtins.TypeError: a bytes-like object is required, not 'str'
```
E ao executar o **demo.py**:

```
Starting "PyPower" as "PyPower-0" ...
Starting "HouseholdSim" as "HouseholdSim-0" ...
Starting "CSV" as "CSV-0" ...
Starting "DeviceAgentSimnode_b5" as "DeviceAgentSimnode_b5-0" ...
ERROR: Simulator "DeviceAgentSimnode_b5" could not be started: Could not connect to "localhost:1234"
Mosaik terminating
```

Você tem alguma ideia do que possa ser e como resolver esses erros para poder executar esse teste?

Obs.: Todas as dependências estão devidamente instaladas e o código está sendo executado em uma virtualenv.

**Comment by lucassm** [comment]
Kelly, você está correta. O erro no demo.py se deve ao fato de o lançamento dos agentes que ocorre no arquivo start_pade_agents.py.

Me parece que o erro ocorre por conta de uma incompatibilidade de versão com o PADE.
Veja a melhor forma de instalar o PADE por meio deste video:

https://asciinema.org/a/ELHfOxZnMUjZyLa8bITJ0AQnP
